common: &common
  adapter: postgresql
  encoding: utf8
  pool: 25
  host: localhost
development:
  database: enapparte_development
  min_messages: warning
  <<: *common
staging:
  database: enapparte_staging
  min_messages: warning
  <<: *common
test:
  database: enapparte_test
  min_messages: warning
  <<: *common
