development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: e43d95de6761822ff6b8d0c0fe9a70e2c4de848b911bfd96e9057ac2e123e49190111a6340b9ee717b3f0d314acf16339c747d506470f9852531357257f0246b
  stripe_api_key: pk_test_6pRNASCoBOKtIshFeQd4XMUh
  default_from_email: user@example.com

test:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: aba855432c4fe4054d69c533c6a2fdb96f76cd8e24e5c8e97479492dc5154d3ab6e40dd65d5d1ee6167c0e55473cfad6ebe04ccca927bfebccfbfec94f45e046
  stripe_api_key: pk_test_6pRNASCoBOKtIshFeQd4XMUh
  default_from_email: user@example.com

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_key: <%= ENV["POSTMARK_API_KEY"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  default_from_email: <%= ENV["DEFAULT_FROM_EMAIL"] %>
